title: 'Tutorial 2 Teaching Guide: Core Skills of a Business Scientist & Introduction to Posit Cloud'
author: Foundations of Business Analytics
date: today
date-format: "MMMM, YYYY"
project:
  render:
    - tutorial.qmd
format:
  html:
    output-file: "tutorial-02-teaching-guide"
    output-ext:  "html"
